const countries = [
    { name: 'Norway', score: 91.89 },
    { name: 'Sweden', score: 88.32 },
    { name: 'Netherlands', score: 87.73 },
    { name: 'Finland', score: 86.55 },
    { name: 'Estonia', score: 86.44 },
    { name: 'Portugal', score: 85.90 },
    { name: 'Ireland', score: 85.59 },
    { name: 'Switzerland', score: 84.01 },
    { name: 'Germany', score: 83.84 },
    { name: 'Luxembourg', score: 83.80 },
    { name: 'Latvia', score: 82.90 },
    { name: 'Lithuania', score: 81.73 },
    { name: 'Canada', score: 81.70 },
    { name: 'Liechtenstein', score: 81.52 },
    { name: 'Belgium', score: 81.49 },
    { name: 'Czechia', score: 80.14 },
    { name: 'Iceland', score: 80.13 },
    { name: 'New Zealand', score: 79.72 },
    { name: 'East Timor', score: 78.92 },
    { name: 'France', score: 78.65 },
    { name: 'Samoa', score: 78.41 },
    { name: 'United Kingdom', score: 77.51 },
    { name: 'Jamaica', score: 77.30 },
    { name: 'Trinidad and Tobago', score: 76.69 },
    { name: 'Costa Rica', score: 76.13 },
    { name: 'Taiwan', score: 76.13 },
    { name: 'Suriname', score: 76.11 },
    { name: 'Slovakia', score: 76.03 },
    { name: 'Spain', score: 76.01 },
    { name: 'Moldova', score: 74.86 },
    { name: 'Austria', score: 74.69 },
    { name: 'Mauritania', score: 74.20 },
    { name: 'Namibia', score: 74.16 },
    { name: 'Dominican Republic', score: 73.89 },
    { name: 'North Macedonia', score: 73.78 },
    { name: 'Seychelles', score: 73.75 },
    { name: 'South Africa', score: 73.73 },
    { name: 'Australia', score: 73.42 },
    { name: 'Montenegro', score: 73.21 },
    { name: 'Cabo Verde', score: 72.77 },
    { name: 'Slovenia', score: 72.60 },
    { name: 'Armenia', score: 71.60 },
    { name: 'Fiji', score: 71.23 },
    { name: 'Tonga', score: 70.11 },
    { name: 'Italy', score: 69.80 },
    { name: 'Poland', score: 69.17 },
    { name: 'Croatia', score: 68.79 },
    { name: 'Romania', score: 68.45 },
    { name: 'Ghana', score: 67.71 },
    { name: 'Uruguay', score: 67.70 },
    { name: 'Chile', score: 67.32 },
    { name: "Côte d'Ivoire", score: 66.89 },
    { name: 'Belize', score: 66.85 },
    { name: 'United States', score: 66.59 },
    { name: 'Gabon', score: 65.83 },
    { name: 'Mauritius', score: 65.55 },
    { name: 'Gambia', score: 65.53 },
    { name: 'Bulgaria', score: 65.32 },
    { name: 'Liberia', score: 65.13 },
    { name: 'Ukraine', score: 65.00 },
    { name: 'South Korea', score: 64.87 },
    { name: 'Malawi', score: 64.46 },
    { name: 'Sierra Leone', score: 64.27 },
    { name: 'Cyprus', score: 63.14 },
    { name: 'Argentina', score: 63.13 },
    { name: 'Hungary', score: 62.98 },
    { name: 'OECS', score: 62.83 },
    { name: 'Congo-Brazzaville', score: 62.57 },
    { name: 'Japan', score: 62.12 },
    { name: 'Comoros', score: 61.47 },
    { name: 'Andorra', score: 61.44 },
    { name: 'Malta', score: 60.96 },
    { name: 'Nepal', score: 60.52 },
    { name: 'Kosovo', score: 60.19 },
    { name: 'Central African Republic', score: 60.12 },
    { name: 'Guyana', score: 60.10 },
    { name: 'Guinea', score: 59.97 },
    { name: 'Botswana', score: 59.78 },
    { name: 'Niger', score: 59.71 },
    { name: 'Bosnia-Herzegovina', score: 58.85 },
    { name: 'Brazil', score: 58.59 },
    { name: 'Panama', score: 58.55 },
    { name: 'Qatar', score: 58.48 },
    { name: 'Eswatini', score: 58.31 },
    { name: 'Burkina Faso', score: 58.24 },
    { name: 'Thailand', score: 58.12 },
    { name: 'Greece', score: 57.15 },
    { name: 'Benin', score: 56.73 },
    { name: 'Northern Cyprus', score: 56.72 },
    { name: 'Papua New Guinea', score: 56.02 },
    { name: 'Guinea-Bissau', score: 55.95 },
    { name: 'Haiti', score: 55.92 },
    { name: 'Senegal', score: 55.44 },
    { name: 'Zambia', score: 55.38 },
    { name: 'Chad', score: 54.81 },
    { name: 'Tanzania', score: 54.80 },
    { name: 'Serbia', score: 54.48 },
    { name: 'Albania', score: 54.10 },
    { name: 'Madagascar', score: 54.07 },
    { name: 'Israel', score: 53.23 },
    { name: 'Kenya', score: 53.22 },
    { name: 'Georgia', score: 53.05 },
    { name: 'Angola', score: 52.44 },
    { name: 'Mozambique', score: 52.42 },
    { name: 'Maldives', score: 52.36 },
    { name: 'Malaysia', score: 52.07 },
    { name: 'Burundi', score: 51.78 },
    { name: 'Mongolia', score: 51.34 },
    { name: 'Ecuador', score: 51.30 },
    { name: 'Indonesia', score: 51.15 },
    { name: 'Nigeria', score: 51.03 },
    { name: 'Togo', score: 50.89 },
    { name: 'Mali', score: 50.56 },
    { name: 'Paraguay', score: 50.48 },
    { name: 'Zimbabwe', score: 50.31 },
    { name: 'Brunei', score: 50.09 },
    { name: 'Tunisia', score: 49.97 },
    { name: 'Colombia', score: 49.63 },
    { name: 'Kyrgyzstan', score: 49.11 },
    { name: 'Mexico', score: 49.01 },
    { name: 'Lesotho', score: 48.92 },
    { name: 'DR Congo', score: 48.91 },
    { name: 'Bolivia', score: 48.88 },
    { name: 'Peru', score: 47.76 },
    { name: 'Singapore', score: 47.19 },
    { name: 'Equatorial Guinea', score: 46.49 },
    { name: 'Uganda', score: 46.00 },
    { name: 'Morocco / Western Sahara', score: 45.97 },
    { name: 'Cameroon', score: 44.95 },
    { name: 'Kuwait', score: 44.66 },
    { name: 'Jordan', score: 44.30 },
    { name: 'El Salvador', score: 44.01 },
    { name: 'Philippines', score: 43.36 },
    { name: 'Hong Kong', score: 43.06 },
    { name: 'South Sudan', score: 42.57 },
    { name: 'Oman', score: 42.52 },
    { name: 'Guatemala', score: 42.28 },
    { name: 'Algeria', score: 41.98 },
    { name: 'Lebanon', score: 41.91 },
    { name: 'Ethiopia', score: 41.37 },
    { name: 'Kazakhstan', score: 41.11 },
    { name: 'Libya', score: 40.59 },
    { name: 'Rwanda', score: 40.54 },
    { name: 'Somalia', score: 39.40 },
    { name: 'Honduras', score: 38.18 },
    { name: 'Bhutan', score: 37.29 },
    { name: 'Uzbekistan', score: 37.27 },
    { name: 'Sudan', score: 35.73 },
    { name: 'Sri Lanka', score: 35.21 },
    { name: 'Cambodia', score: 34.28 },
    { name: 'Pakistan', score: 33.90 },
    { name: 'Laos', score: 33.76 },
    { name: 'Yemen', score: 33.67 },
    { name: 'Tajikistan', score: 33.31 },
    { name: 'Venezuela', score: 33.06 },
    { name: 'Palestine', score: 31.92 },
    { name: 'Türkiye', score: 31.60 },
    { name: 'India', score: 31.28 },
    { name: 'United Arab Emirates', score: 30.62 },
    { name: 'Djibouti', score: 30.14 },
    { name: 'Russia', score: 29.86 },
    { name: 'Nicaragua', score: 29.20 },
    { name: 'Azerbaijan', score: 27.99 },
    { name: 'Bangladesh', score: 27.64 },
    { name: 'Saudi Arabia', score: 27.14 },
    { name: 'Belarus', score: 26.80 },
    { name: 'Cuba', score: 25.63 },
    { name: 'Iraq', score: 25.48 },
    { name: 'Egypt', score: 25.10 },
    { name: 'Myanmar', score: 24.41 },
    { name: 'China', score: 23.36 },
    { name: 'Bahrain', score: 23.21 },
    { name: 'Vietnam', score: 22.31 },
    { name: 'Turkmenistan', score: 22.01 },
    { name: 'Iran', score: 21.30 },
    { name: 'North Korea', score: 20.66 },
    { name: 'Afghanistan', score: 19.09 },
    { name: 'Syria', score: 17.41 },
    { name: 'Eritrea', score: 16.64 }
];
